/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package livraria.interfaces;

import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import livraria.controllers.ControllerClientes;
import livraria.controllers.ControllerLivros;
import livraria.controllers.ControllerPedidos;
import livraria.modelos.Cliente;
import livraria.modelos.Endereco;
import livraria.modelos.ItemPedido;
import livraria.modelos.Livro;
import livraria.modelos.Pedido;

/**
 *
 * @author thales.pereira
 */
public class InterfacePedidoFormulario extends javax.swing.JFrame {

    Integer posicaoPedido;
    
    ControllerLivros controllerLivros;
    ControllerClientes controllerClientes;
    ControllerPedidos controllerPedidos = ControllerPedidos.getInstance();
    
    DefaultTableModel itemPedidoModel;
    
    /**
     * Creates new form InterfacePedidoFormulario
     */
    public InterfacePedidoFormulario() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        controllerClientes = ControllerClientes.getInstance();
        controllerLivros = ControllerLivros.getInstance();
        
        DefaultComboBoxModel clienteModel = new DefaultComboBoxModel();
        
        for (Cliente cliente : controllerClientes.todos())
            clienteModel.addElement(cliente);
        
        cbClientes.setModel(clienteModel);
        
        
        DefaultComboBoxModel livroModel = new DefaultComboBoxModel();
        
        for (Livro livro : controllerLivros.todos())
            livroModel.addElement(livro);
        
        cbProduto.setModel(livroModel);
        
        
        itemPedidoModel = new DefaultTableModel();
        
        itemPedidoModel.addColumn("Titulo");
        itemPedidoModel.addColumn("Quantidade");
        itemPedidoModel.addColumn("Valor Unidade");
        itemPedidoModel.addColumn("Valor Total");
        
        tableItemPedido.setModel(itemPedidoModel);
        

        Date hoje = new Date();
        tfDataEmissao.setText(new SimpleDateFormat("d/M/yy", Locale.ENGLISH).format(hoje));
    }
    
    public void completarCampos(int posicao) {
        posicaoPedido = posicao;
        
        Pedido pedido = controllerPedidos.todos().get(posicao);
        
        cbClientes.setSelectedItem(pedido.getCliente());
        
        DecimalFormat df = new DecimalFormat("0.00");
        
        for (ItemPedido itemPedido : pedido.getItensPedidos()) {
            Object ob [] = {
                itemPedido.getLivro(), 
                itemPedido.getQuantidade(),
                itemPedido.getLivro().getPreco(),
                itemPedido.getLivro().getPreco() * itemPedido.getQuantidade()
            };
            itemPedidoModel.addRow(ob);
        }
        
        if(pedido.getDataEmissao()!=null) {
            DateFormat dfo = new SimpleDateFormat("d/M/yy", Locale.ENGLISH);
            this.tfDataEmissao.setText(dfo.format(pedido.getDataEmissao()));
        }
        
        lValorTotal.setText(Float.toString(pedido.getValorTotal()));
        cbFormaPagamento.setSelectedItem(pedido.getFormaPagamento());
        cbSituacao.setSelected(pedido.isSituacao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbFormaPagamento = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbSituacao = new javax.swing.JCheckBox();
        btSalvar = new javax.swing.JButton();
        btAdicionarItem = new javax.swing.JButton();
        sQuantidade = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btRemover = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btCancelar = new javax.swing.JButton();
        cbProduto = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cbClientes = new javax.swing.JComboBox();
        lValorTotal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableItemPedido = new javax.swing.JTable();
        tfDataEmissao = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pedido");

        jLabel2.setText("Data Emissão");

        cbFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cartão de Crédito", "À Vista", "Débito" }));

        jLabel3.setText("Forma de Pag");

        jLabel4.setText("Valor Total");

        cbSituacao.setText("Situação");
        cbSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSituacaoActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btAdicionarItem.setText("Adicionar");
        btAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarItemActionPerformed(evt);
            }
        });

        sQuantidade.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        sQuantidade.setValue(1);

        jLabel5.setText("Quantidade");

        jLabel6.setText("Livro");

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        jLabel7.setText("Livros Adicionados");

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        cbProduto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Cliente");

        cbClientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lValorTotal.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lValorTotal.setText("0.00");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel9.setText("R$");

        tableItemPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableItemPedido);

        tfDataEmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yy"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbSituacao)
                                        .addContainerGap())
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btAdicionarItem))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbFormaPagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btCancelar)
                                .addGap(231, 231, 231))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lValorTotal)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbSituacao)
                    .addComponent(tfDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAdicionarItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRemover))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lValorTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSituacaoActionPerformed

    private void btAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarItemActionPerformed
        Livro livroSelecionado = controllerLivros.todos().get(cbProduto.getSelectedIndex()); 
        Float valorItem = livroSelecionado.getPreco();
       
        DecimalFormat df = new DecimalFormat("0.00");
        
        Object ob [] = {livroSelecionado, sQuantidade.getValue(), livroSelecionado.getPreco(), df.format(valorItem * (Integer) sQuantidade.getValue())};
        itemPedidoModel.addRow(ob);
        
        Float valorTotalAtual = Float.parseFloat(lValorTotal.getText());
        Float total = valorTotalAtual + (valorItem * (Integer) sQuantidade.getValue());
        
        lValorTotal.setText(df.format(total));
        
        sQuantidade.setValue(1);
    }//GEN-LAST:event_btAdicionarItemActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
 
        Pedido novoPedido = new Pedido();
        
        List<ItemPedido> listItensPedidos = new ArrayList();
        
        for(int i = 0 ; i<tableItemPedido.getRowCount() ; i++) {
            ItemPedido itemPedido = new ItemPedido();
            itemPedido.setLivro((Livro) tableItemPedido.getValueAt(i, 0));
            itemPedido.setQuantidade(Integer.parseInt(tableItemPedido.getValueAt(i, 1).toString()));
            itemPedido.setPreco(Float.parseFloat(tableItemPedido.getValueAt(i, 2).toString()));
            
            listItensPedidos.add(itemPedido);
        }
        
        novoPedido.setItensPedidos(listItensPedidos);

        int ultimoNumero = 1;
        
        if (controllerPedidos.todos().size()>0) {
            ultimoNumero = controllerPedidos.todos().get(controllerPedidos.todos().size()-1).getNumero() + 1;
        }
        
        try {
            Date date = new SimpleDateFormat("d/M/yy", Locale.ENGLISH).parse(tfDataEmissao.getText());
            novoPedido.setDataEmissao(date);
        } catch (ParseException e) {
            
        }

        novoPedido.setValorTotal(Float.parseFloat(lValorTotal.getText()));
        novoPedido.setFormaPagamento(cbFormaPagamento.getSelectedItem().toString());
        novoPedido.setSituacao(cbSituacao.isSelected());
        
        Cliente cliente = (Cliente) cbClientes.getSelectedItem();
        novoPedido.setCliente(cliente);
        
        Endereco endereco = new Endereco();
        
        endereco.setBairro(cliente.getBairro());
        endereco.setCEP(cliente.getCEP());
        endereco.setCidade(cliente.getCidade());
        endereco.setComplemento(cliente.getComplemento());
        endereco.setEstado(cliente.getEstado());
        endereco.setNumero(cliente.getNumero());
        endereco.setRua(cliente.getRua());
        
        novoPedido.setEntrega(endereco);
        
        try {
            Date date = new SimpleDateFormat("d/M/yy", Locale.ENGLISH).parse(tfDataEmissao.getText());
            novoPedido.setDataEmissao(date);
        } catch (ParseException e) {
            
        }
        
        if (posicaoPedido==null) {
            novoPedido.setNumero(ultimoNumero);
            controllerPedidos.salvar(novoPedido);
        } else {
            controllerPedidos.atualizar(posicaoPedido, novoPedido);            
        }
        
        btCancelarActionPerformed(evt);
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        new InterfacePedido().setVisible(true);
        dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        int position = tableItemPedido.getSelectedRow();
        
        if (position>=0) {
            float valorTotal = Float.parseFloat(tableItemPedido.getValueAt(position, 3).toString());
            float valorTotalAtual = Float.parseFloat(lValorTotal.getText());
            
            DecimalFormat df = new DecimalFormat("0.00");
            
            lValorTotal.setText(df.format(valorTotalAtual - valorTotal));
            
            itemPedidoModel.removeRow(position);
        }
    }//GEN-LAST:event_btRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePedidoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePedidoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePedidoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePedidoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePedidoFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarItem;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cbClientes;
    private javax.swing.JComboBox cbFormaPagamento;
    private javax.swing.JComboBox cbProduto;
    private javax.swing.JCheckBox cbSituacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lValorTotal;
    private javax.swing.JSpinner sQuantidade;
    private javax.swing.JTable tableItemPedido;
    private javax.swing.JFormattedTextField tfDataEmissao;
    // End of variables declaration//GEN-END:variables
}
